baseURL = "https://vibrant-beaver-8c9ce5.netlify.com/"
languageCode = "en-us"
title = "Zachary Glassman"
theme = "forty"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Zachary Glassman"
  description = "data scientist, cat daddy"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Zachary Glassman"
    subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Resume"
      url = "img/resume.pdf"

    [[params.navigation.links]]
      name = "Professional"
      url = "page/professional"

    [[params.navigation.links]]
      name = "Personal"
      url = "page/personal"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, I'm Zach"
    subtitle = "data scientist, cat daddy, "
    buttonText = "About me"
    text = "I am a Data Scientist in Residence at the Data Incubator in the lovely San Francisco Bay Area. I instruct people in all sorts of data sciency things ranging from machine learning to python to visualization while also working on software engineering/devops projects."


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Resume"
      subtitle = ""
      image = ""
      url = "img/resume.pdf"

    [[params.tiles.showcase]]
      title = "Projects"
      subtitle = ""
      image = ""
      url = "https://github.com/zachglassman"

    [[params.tiles.showcase]]
      title = "Professional Interests"
      subtitle = "What I'm currently playing around with"
      image = ""
      url = "page/professional"

    [[params.tiles.showcase]]
      title = "Personal Interests"
      subtitle = "A few things I like to do"
      image = ""
      url = "page/personal"


  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "zach.glassman@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons



    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/zachglassman"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/zachary-glassman-7088844b/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
